#include "types.h"
#include "param.h"
#include "memlayout.h"
#include "riscv.h"
#include "spinlock.h"
#include "proc.h"
#include "syscall.h"
#include "defs.h"

# OBJS += proj1/kernel/syscall.o


# OBJS += proj1/kernel/somefile.o