#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define MAX_LINE_LENGTH 256

int main(int argc, char *argv[]) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <output_file>\n", argv[0]);
        return 1;
    }

    // Open syscall.h for reading
    FILE *syscall_h = fopen("kernel/syscall.h", "r");
    if (!syscall_h) {
        fprintf(stderr, "Error opening syscall.h file\n");
        return 1;
    }

    // Open the user-provided output file
    FILE *output = fopen(argv[1], "w");
    if (!output) {
        fprintf(stderr, "Error creating %s file\n", argv[1]);
        fclose(syscall_h);
        return 1;
    }

    // Header in the output file
    fprintf(output, "# generated by usys.c - do not edit\n#include \"kernel/syscall.h\"\n");

    char line[MAX_LINE_LENGTH];
    while (fgets(line, sizeof(line), syscall_h)) {
        // Look for lines starting with "#define SYS_"
        if (strncmp(line, "#define SYS_", 12) == 0) {
            char syscall_name[50];

            // Extract the system call name and number
            if (sscanf(line, "#define SYS_%s", syscall_name) == 1) {
                // Write the assembly stub for this system call, using the syscall name
                fprintf(output, ".global %s\n", syscall_name);
                fprintf(output, "%s:\n", syscall_name);
                fprintf(output, " li a7, SYS_%s\n", syscall_name);  
                fprintf(output, " ecall\n");                    // Make the syscall
                fprintf(output, " ret\n");                    // Return
            }
        }
    }

    fclose(syscall_h);
    fclose(output);

    printf("Assembly stubs successfully generated in %s.\n", argv[1]);

    return 0;
}
